
title: 개발공부용 깃허브
url: 'https://sungbumvv.github.io'
baseurl: '' #change it according to your repository name



# Profile information
yourname: 이성범  ## put your name
title: '초보 웹개발자'  ## your title
location: 서울시 도봉구 쌍문4동 


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
